# vim: nospell
#
language: c
dist: trusty

cache:
  timeout: 600
  directories:
    - $HOME/.stack
    - $HOME/.local/bin
    - $TRAVIS_BUILD_DIR/.stack-work

before_cache:
  - rm -f $HOME/.stack/programs/*/*.tar.bz2

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc

    packages: &apt_packages
      - alex-3.1.7
      - happy-1.19.5

compiler:
  - GHC-8.6.5
  - GHC-8.4.4
  - GHC-8.2.2
  - GHC-8.0.2
  - GHC-7.10.3
  - GHC-7.8.4

env:
  # global:
  matrix:
    - CUDA=10.1.105-1
    # - CUDA=10.0.130-1
    # - CUDA=8.0.61-1
    # - CUDA=7.5-18
    # - CUDA=7.0-28
    # - CUDA=6.5-14

matrix:
  fast_finish: true
  # allow_failures:

before_install:
  - export GHC=${CC:4}
  - unset CC
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - export CUDA_INSTALL_EXTRA_LIBS=0
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version; true
  - nvcc --version; true

install:
  - export FLAGS="--fast --no-terminal --no-copy-bins --no-interleaved-output"
  - travis_retry stack build --only-dependencies

script:
  - travis_retry stack build --haddock --no-haddock-deps

after_success:
  - source .travis/update-accelerate-buildbot.sh

after_failure:
  - ls -R /usr/local/cuda*
  - dmesg

